- name: Installing nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: placing expense config file in nginx
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: include app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prereq

- name: starting nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes